# Generated by Django 5.2.4 on 2025-07-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primera_app', '0002_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tatuaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_turno', models.DateField()),
                ('email_contacto', models.EmailField(max_length=254)),
                ('edad_cliente', models.IntegerField()),
            ],
        ),
    ]
