# Generated by Django 5.2.4 on 2025-07-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primera_app', '0004_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tatuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=50)),
                ('experiencia_anios', models.IntegerField(default=0)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
