# Generated by Django 5.2.4 on 2025-07-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primera_app', '0005_tatuador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
