# Generated by Django 5.2.4 on 2025-07-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primera_app', '0008_alter_inscripcion_curso_and_more'),
        ('usuarios', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tatuador',
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='usuarios.profesor'),
        ),
        migrations.AddField(
            model_name='tatuaje',
            name='tatuador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tatuador'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion_semanas',
            field=models.IntegerField(),
        ),
    ]
