# Generated by Django 5.2.4 on 2025-07-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primera_app', '0009_delete_tatuador_curso_profesor_tatuaje_tatuador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatuaje',
            name='descripcion',
            field=models.TextField(default='Sin descripción disponible'),
        ),
    ]
