# Generated by Django 5.2.4 on 2025-08-03 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primera_app', '0010_alter_tatuaje_descripcion'),
        ('usuarios', '0005_remove_tatuador_estilos_estilotatuaje_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatuaje',
            name='estilo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.estilotatuaje'),
        ),
    ]
