# Generated by Django 5.2.4 on 2025-08-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primera_app', '0011_tatuaje_estilo'),
        ('usuarios', '0005_remove_tatuador_estilos_estilotatuaje_creador'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoTatuaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('edad_cliente', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_turno', models.DateField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estilotatuaje')),
                ('tatuador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tatuador')),
            ],
        ),
    ]
