# Generated by Django 5.2.4 on 2025-08-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primera_app', '0012_turnotatuaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatuaje',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción disponible'),
        ),
        migrations.AlterField(
            model_name='tatuaje',
            name='edad_cliente',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='TurnoTatuaje',
        ),
    ]
