# Generated by Django 5.2.4 on 2025-08-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloTatuaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='tatuador',
            name='estilos',
            field=models.ManyToManyField(blank=True, related_name='tatuadores', to='usuarios.estilotatuaje'),
        ),
    ]
