# Generated by Django 5.2.4 on 2025-08-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_estilotatuaje_tatuador_estilos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tatuador',
            name='estilos',
        ),
        migrations.AddField(
            model_name='estilotatuaje',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estilos_creados', to='usuarios.tatuador'),
        ),
    ]
